print( '*' * 10 + ' Converting from float to int data types ' + '*' * 10)
a = int(10.9898)
print(a)
print('*' * 10 + ' Converting from int to float data types ' + '*'  * 10)
b = float(10)
print(b)
print ('*' * 10 + ' converting from boolean  to int data types ' + '*' * 10)
c = int(True)
print(c)
d = int(False)
print(d)
print ('*' *  20)
print("Complex type can't be converted to the int data types")